# Generated by Django 5.1.7 on 2025-03-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectdate', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=200)),
                ('logout', models.CharField(max_length=200)),
                ('selectworkout', models.CharField(max_length=200)),
                ('trainedby', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='datejoined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
