# Generated by Django 5.1.7 on 2025-03-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_attendance_trainer_datejoined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='workout/')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('img', models.ImageField(upload_to='session/')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.trainer')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.workout')),
            ],
        ),
    ]
