# Generated by Django 5.1.7 on 2025-03-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_session_capacity_trainer_user_alter_session_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
